services:
  eien:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/eien/data
    ports:
      - '6969:6969'
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 100M
